-- MySQL Script generated by MySQL Workbench
-- 01/16/18 23:53:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kivbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kivbook` ;

-- -----------------------------------------------------
-- Schema kivbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kivbook` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `kivbook` ;

-- -----------------------------------------------------
-- Table `kivbook`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kivbook`.`user` ;

CREATE TABLE IF NOT EXISTS `kivbook`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(500) NOT NULL,
  `birth_date` DATE NULL,
  `gender` VARCHAR(255) NULL,
  `profile_visibility` VARCHAR(255) NOT NULL,
  `social_identity_provider` VARCHAR(255) NULL,
  `profile_photo` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kivbook`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kivbook`.`post` ;

CREATE TABLE IF NOT EXISTS `kivbook`.`post` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `date_posted` DATE NULL,
  `time_posted` TIME NULL,
  `text` VARCHAR(1000) NOT NULL,
  `visibility` VARCHAR(255) NOT NULL,
  `owner_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user_idx` (`owner_id` ASC),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`owner_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kivbook`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kivbook`.`message` ;

CREATE TABLE IF NOT EXISTS `kivbook`.`message` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `timestamp` TIMESTAMP NULL,
  `state` VARCHAR(255) NOT NULL,
  `sender_id` BIGINT(20) NOT NULL,
  `receiver_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user1_idx` (`sender_id` ASC),
  INDEX `fk_message_user2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kivbook`.`friend_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kivbook`.`friend_request` ;

CREATE TABLE IF NOT EXISTS `kivbook`.`friend_request` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_date` DATE NULL,
  `responded_date` DATE NULL,
  `friend_request_state` VARCHAR(255) NOT NULL,
  `sender_id` BIGINT(20) NOT NULL,
  `receiver_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_friend_request_user1_idx` (`sender_id` ASC),
  INDEX `fk_friend_request_user2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_friend_request_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_request_user2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kivbook`.`conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kivbook`.`conversation` ;

CREATE TABLE IF NOT EXISTS `kivbook`.`conversation` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_user_id` BIGINT(20) NOT NULL,
  `second_user_id` BIGINT(20) NOT NULL,
  `last_message_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conversation_user1_idx` (`first_user_id` ASC),
  INDEX `fk_conversation_user2_idx` (`second_user_id` ASC),
  INDEX `fk_conversation_message1_idx` (`last_message_id` ASC),
  CONSTRAINT `fk_conversation_user1`
    FOREIGN KEY (`first_user_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_user2`
    FOREIGN KEY (`second_user_id`)
    REFERENCES `kivbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_message1`
    FOREIGN KEY (`last_message_id`)
    REFERENCES `kivbook`.`message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
